CREATE TABLE UTENTI (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOME TEXT(100) NOT NULL,
	COGNOME TEXT(100) NOT NULL,
	EMAIL TEXT(100) NOT NULL,
	PASSWORD TEXT(100) NOT NULL,
	CAP INTEGER,
	INDIRIZZO TEXT(255),
	CIVICO TEXT(10),
	CITTA INTEGER,
	PROVINCIA TEXT(100),
	NOTE TEXT(4000)
);

CREATE TABLE NEWSLETTER (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	EMAIL TEXT(100) NOT NULL
);

CREATE TABLE PRODOTTI (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NOME TEXT(100) NOT NULL,
	DESCRIZIONE TEXT(255) NOT NULL,
	PREZZO REAL,
	IMMAGINE TEXT(255),
	CATEGORIA TEXT(100),
	COLORE TEXT(100),
	MATERIALE TEXT(100),
	DATA_INSERIMENTO TEXT(10)
);

CREATE TABLE WISHLIST (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ID_PRODOTTO INTEGER NOT NULL,
    ID_UTENTE INTEGER NOT NULL,
    CONSTRAINT fk_prodotto FOREIGN KEY (ID_PRODOTTO) REFERENCES PRODOTTI(ID),
    CONSTRAINT fk_utente FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);

CREATE TABLE CARRELLO (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	NUMERO_ORDINE TEXT(10),
	NOTE TEXT(255),
    ID_UTENTE INTEGER NOT NULL,
    CONSTRAINT fk_utente FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID)
);
